### PR TITLE
Add GitHub Actions problem matchers to CI

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Very nice to see this working. Can be merged after dropping the test commit, as far as I'm concerned :)

**Comment by LeftofZen** [comment]
I don't fully understand what this is, but it sounds really cool

**Comment by janisozaur** [comment]
@LeftofZen it does this:
image

**Review by AaronVanGeffen — APPROVED** [review]

**Comment by LeftofZen** [comment]
So github can can parse and display the errors of a compilation in a nice format?

**Comment by janisozaur** [comment]
Pretty much

**Pull request merged**
