### PR TITLE
add unit tests

### PR DESCRIPTION
**Pull request by LeftofZen**
adds unit tests to openloco
#73

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
I've reorged the vcxproj and sln file to follow more like the main project. Now its getting the dependency from our prepackaged ones.

**Comment by LeftofZen** [comment]
It may not be possible to successfully link and build the unit tests whilst the code is still in a partial-reverse-engineered state, it may only be possible to do after openloco is standalone.

**Comment by LeftofZen** [comment]
Whilst the current branch here builds and runs the dummy test, once you reference anything from OpenLoco there are linker errors. An example test is this:

```
#include <OpenLoco/Date.h>
#include <gtest/gtest.h>

namespace Testing
{
    TEST(TestIsLeapYear, DateTests)
    {
        ASSERT_TRUE(OpenLoco::isLeapYear(193));
    }
}
```

If anyone knows a way to resolve the linker errors that would be amazing.

**Comment by LeftofZen** [comment]
Naturally just as I write it's impossible, I figured out one way to do it, see latest commit

**Comment by duncanspumpkin** [comment]
Unit tests can now be added with the updated cmake.

**Pull request closed without merging**
