### PR TITLE
Remove interop for _paintHead, refactor uses, isolate PaintEntry

### PR DESCRIPTION
**Pull request by ZehMatt**
This much I can already refactor without breaking any existing interop code, there is mostly the bridges left but this has no effect on it.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
This will need at least the final add to plot list function implemented

**Comment by ZehMatt** [comment]
> This will need at least the final add to plot list function implemented

Not sure, this variable is not used to add new paint structs, its used to sort it and when rendered which we already cover.

**Comment by duncanspumpkin** [comment]
Ahh yes sorry got it confused with another var. Should this just become a local variable rather than a member var?

**Comment by ZehMatt** [comment]
> Ahh yes sorry got it confused with another var. Should this just become a local variable rather than a member var?

Not sure, maybe, I will have to think about that later when I can freely move things around.

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
