### PR TITLE
Remove windows.h dependency, set hint for icon resource to SDL

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
This looks like it would no longer be using the OpenLoco icon stored in the `openloco.dll`. Is that a deliberate change?

**Comment by ZehMatt** [comment]
> This looks like it would no longer be using the OpenLoco icon stored in the `openloco.dll`. Is that a deliberate change?

What makes you think that? The resource is still embedded and that is also what SDL will use when the hint is supplied.

**Comment by ZehMatt** [comment]
> > This looks like it would no longer be using the OpenLoco icon stored in the `openloco.dll`. Is that a deliberate change?
> 
> What makes you think that? The resource is still embedded and that is also what SDL will use when the hint is supplied.
> 
> Edit: image image

Edit 2: I think I see what you mean

**Comment by ZehMatt** [comment]
I didn't realize the binary still had the original Icon on it so yeah this will not work this way.

**Pull request closed without merging**
