### PR TITLE
Dump Russian script

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Cool! Nice find. 👍

**Comment by AaronVanGeffen** [comment]
@marijnvdwerf I notice this is tagged WIP. Aside from not actually supporting Cyrillic glyphs yet, are there anything stoppers for a merge?

**Comment by marijnvdwerf** [comment]
Just not being 100% sure about the quality of the translation and dump. But I guess a bad translation is still better than no translation.

**Comment by janisozaur** [comment]
> I guess a bad translation is still better than no translation

You must've not been exposed to bad translations then.

**Pull request merged**
