### PR TITLE
Vehicle Tool Down

### PR DESCRIPTION
**Pull request by duncanspumpkin**
So it seems there are yet more arguments!

### CODE REVIEW

**Review by AaronVanGeffen — CHANGES_REQUESTED** [review]
I'm having trouble placing down any kind of vehicle on this PR. Buses and trains appear briefly as a ghost _when clicking_, but immediately disappear again.

**Comment by duncanspumpkin** [comment]
Okay i might have rushed the last bit and not tested land vehicles

**Comment by duncanspumpkin** [comment]
Okay found the issue forgot to initialise a variable to false.

**Review by AaronVanGeffen — APPROVED** [review]
Works as expected now. Nice work!

**Pull request merged**
