### PR TITLE
Update pl-PL.yml

### PR DESCRIPTION
**Pull request by Zcooger**

### CODE REVIEW

**Comment by Zcooger** [comment]
Truncated text fix
image

**Comment by Zcooger** [comment]
image

**Comment by AaronVanGeffen** [comment]
Which do you prefer? I wouldn't mind widening the option window either.

**Comment by AaronVanGeffen** [comment]
I just remembered that we were going to widen the window anyway, because of the German strings:

Untitled

**Comment by Zcooger** [comment]
I guess I'll extend the strings for this window then.

**Comment by Zcooger** [comment]
image

**Pull request merged**
