### PR TITLE
[WIP] Run OpenLoco on macOS via Docker Desktop

### PR DESCRIPTION
**Pull request by tomasharkema**
This PR aims to add macOS 64-bit (_development!_) support by some demand.

Some todo's
- [ ] hit a Segmentation Fault while running
- [x] add a script to accommodate starting
- [ ] Tried to add compose file... hard to make ENV's work. Delete?
- [ ] Cleanup apt-get
- [ ] Cleanup placement of files
- [x] make audio work

Checks:
- [ ] M1 macs (aarch64)?

Considerations:
- [ ] Publish docker image via docker hub, don't rely on users checking it out 

More idea's
- [ ] maybe Xvnc will be a more performant and easier way to do this...

### CODE REVIEW

**Comment by tomasharkema** [comment]
While debugging with `gdb`, in release mode I hit the following `SIGSEGV`:

```
Program received signal SIGSEGV, Segmentation fault.
0x011a39a9 in OpenLoco::Interop::callByRef(int, int*, int*, int*, int*, int*, int*, int*) ()
(gdb)
```

**Comment by AaronVanGeffen** [comment]
Thanks for the PR. This looks like it'll be a useful addition for macOS users.

> While debugging with `gdb`, in release mode I hit the following `SIGSEGV`:

Is the stack in a state where a any backtrace can be generated? (`bt`)

**Comment by tomasharkema** [comment]
When I run `bt`:
```
(gdb) bt
#0  0x011a39a9 in OpenLoco::Interop::callByRef(int, int*, int*, int*, int*, int*, int*, int*) ()
#1  0x012ae000 in ?? ()
#2  0x01166e78 in main ()
```

**Comment by AaronVanGeffen** [comment]
While this was a promising approach, the current recommended [route for running OpenLoco on macOS](https://github.com/OpenLoco/OpenLoco/wiki/Running-OpenLoco-on-macOS) is through Wine. Combined with building through a MinGW Docker (see our CI images), this makes it even viable for dev purposes, too, surprisingly.

**Pull request closed without merging**
