### PR TITLE
Port over OpenRCT2 Draw sprite

### PR DESCRIPTION
**Pull request by duncanspumpkin**
~~WiP doesn't quite work atm needs still some work haven't brought over the RLE sprites. Also tree wilt is broken in this atm as that did not exist in OpenRCT2.~~

~~Still to do treeWilt for RLE sprites. (Not sure if they even have tree wilt)~~ No they dont do tree wilt so all done.

Complete

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
This is based on the OpenRCT2 code which i have further templatised and improved.

**Comment by AaronVanGeffen** [comment]
I'll do some playtesting on this branch on the weekend.

**Review by AaronVanGeffen — APPROVED** [review]
Testing this, the game is a fair bit slower in unoptimised debug mode (from ~34fps to ~24fps). This is to be expected, I suppose, with performance-critical parts of the game now implemented in C++. Thankfully, this effect is absent when compiled in `RelWithDebInfo` mode (stays between 50~60fps for me)

In my limited playtesting, I haven't noticed any abnormalities, nor have I run into #1522. I'd appreciate someone else reviewing this on Windows as well though, just in case.

**Comment by duncanspumpkin** [comment]
> Testing this, the game is a fair bit slower in unoptimised debug mode (from ~34fps to ~24fps). This is to be expected, I suppose, with performance-critical parts of the game now implemented in C++. Thankfully, this effect is absent when compiled in `RelWithDebInfo` mode (stays between 50~60fps for me)
> 
> In my limited playtesting, I haven't noticed any abnormalities, nor have I run into #1522. I'd appreciate someone else reviewing this on Windows as well though, just in case.

Oh that is somewhat surprising i had increased frame rate in debug builds. #1522 would be fixed by this as its just due to the way globals are used to pass values around which i've removed in my code.

**Review by LeftofZen — APPROVED** [review]

**Pull request merged**
