### PR TITLE
Fix train station again

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Another month another issue with train stations. I think this now makes sense as it matches how the road ones work.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Anything in particular that should be tested?

**Comment by duncanspumpkin** [comment]
> Anything in particular that should be tested?

It's clearance related but I'm not entirely sure in what situations that becomes critical. Would suggest using one of the train station styles that have extra height clearance check you can't build when something is just above the track. Need to check against master as well

**Review by AaronVanGeffen — APPROVED** [review]
I am able to build stations fine with this PR, both overground and underground, both with and without deliberate obstructions (buildings, trees). But honestly, I haven't been experiencing any problems with any of those on master, either. I trust this PR is more correct, though.

**Comment by duncanspumpkin** [comment]
[MMTest100000_base.zip](https://github.com/OpenLoco/OpenLoco/files/14736893/MMTest100000_base.zip)
For reference this is the new reference after 100000 ticks.

**Pull request merged**
