### PR TITLE
Force alignment on TileManager::createAnimation hook

### PR DESCRIPTION
**Pull request by AaronVanGeffen**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
@janisozaur I believe this may have been the cause for the crashes you were experiencing yesterday.

**Comment by janisozaur** [comment]
I wonder if it is - the previous crashes were due to SSE2 code requiring specific alignment, but the crashes I observed lately were in vanilla code and on Ubuntu, which doesn't have SSE enabled.

@AaronVanGeffen as you were able to reproduce those, have you seen them fixed?

**Comment by AaronVanGeffen** [comment]
Yes, those crashes were fixed by the last commit that addressed hooks. I was hoping this one, introduced by merging the load branch, would be responsible for the crash you were experiencing.

**Comment by AaronVanGeffen** [comment]
@duncanspumpkin It was introduced by #921, while the hooks were updated before that PR was merged.

**Comment by janisozaur** [comment]
Do you guys think it's possible to have some code to verify those hooks continuously?

**Comment by duncanspumpkin** [comment]
We discussed scrapping this type of hook and reverting to the openrct2 hook but will need some thinking to remind myself what needs done to achieve that.

**Comment by janisozaur** [comment]
Sorry to disappoint, but the crash persists on this change.

**Review by janisozaur — APPROVED** [review]

**Pull request merged**
