### PR TITLE
Formatter refactor

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Thought we could do with having a constructor that lets us add the items we need immediately rather than having to do lots of pushes. Also shows off a cpp fold expression as a test to see if all the ci's can handle it.

### CODE REVIEW

**Review by AaronVanGeffen — APPROVED** [review]

**Comment by AaronVanGeffen** [comment]
This nicely reduces some of the verbosity associated with FormatArgs objects. I think we should not mix the brace initialiser introduced here with the other style of pushing arguments, though. (This PR is fine on that front.)

**Comment by duncanspumpkin** [comment]
This is going to cause a collision with #670. Trying to think the best solution.

**Comment by duncanspumpkin** [comment]
I've modified this so that you have to specify `common` for the formatter to default to the common format arguments. I'm going to do a follow on PR that forces you to select which format arguments to use to make it clear the global connection. Then we can eventually free up the default constructor for when we don't use a global.

**Review by AaronVanGeffen — COMMENTED** [review]
Sounds good. However, CI is current failing. Could you address the errors?

**Comment by duncanspumpkin** [comment]
Argh keep forgetting returns. Doh

**Pull request merged**
