### PR TITLE
reduce locoglobals - remove 0x0113600C as it isn't used

### PR DESCRIPTION
**Pull request by LeftofZen**
Unsure on the best name since I don't know what this function/memory location does, but it seems to set the viewport interaction location for some later computation?

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
I'm pretty sure it's unused. It was a local variable for the function but we didn't use it.

**Comment by LeftofZen** [comment]
oh ok, so I'll just remove all these lines entirely?

**Comment by duncanspumpkin** [comment]
> oh ok, so I'll just remove all these lines entirely?

Yeah try removing it and confirm nothing blows up.

**Comment by duncanspumpkin** [comment]
yeah its safe to remove.

**Comment by LeftofZen** [comment]
I removed it and played for 5 mins, tried to place a bunch of things and had no issues

**Review by AaronVanGeffen — COMMENTED** [review]
Before merging, please adjust the commit message to read removal instead.

**Review by duncanspumpkin — APPROVED** [review]

**Review by AaronVanGeffen — APPROVED** [review]

**Pull request merged**
