### PR TITLE
Add a screenshot to the readme file

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
A user on Reddit [suggested](https://www.reddit.com/r/locomotion/comments/aw889a/openloco_release_v1902/ehkwrqm/) we add a few screenshot to the GitHub page. I don't want to clutter the readme file too much, but this PR adds a simple one at least, showcasing a macOS build.

Perhaps we should link a few more further down in the file. Any suggestions?

Current screenshot:

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Other idea:
screenshot 2019-03-01 at 22 10 03

**Comment by IntelOrca** [comment]
First screenshot doesn't show much and has old logo which we will eventually change. Second screenshot is a bit too messy. I think we need one with a nice multi train station, junction next to a town.

**Comment by AaronVanGeffen** [comment]
Yes, I agree. I don't have very nice save files laying around though…

**Comment by AaronVanGeffen** [comment]
Some ideas from saves I had around.

Screenshot_20190316_181924

Screenshot_20190316_182019

Screenshot_20190316_182120

Screenshot_20190316_182144

**Comment by IntelOrca** [comment]
Maybe the one with the power station? You will want to crop the UI out the screenshot too or un mute the game.

**Comment by AaronVanGeffen** [comment]
Something like this?

Screenshot_20190316_211942

**Comment by IntelOrca** [comment]
Yes, although I was thinking of the other one with the power station.

**Comment by marijnvdwerf** [comment]
I find the power central rather unsightly. Would be prefer one of the first two pictures from <https://github.com/OpenLoco/OpenLoco/pull/291#issuecomment-473567231>, but with the labels removed. Something in the vibe of http://www.transporttycoon.com/img/media/big/b2.jpg (but with a 21:9 aspect ratio, to not push the content down too much).

**Comment by AaronVanGeffen** [comment]
OK, here's the map from second screenshot from the above comment with a bigger viewport:

Screenshot_20190402_183453

Proposed 21:9 crop:

Screenshot_20190402_183453_21_9

Thoughts? Feel free to propose something else, too.

**Pull request merged**
