### PR TITLE
Implement/exception popups

### PR DESCRIPTION
**Pull request by rdrdrdrd95**
Added generic definition and platform specific implementation for Windows of system message popups for exception handling outside of debug mode. 

Hooks for other platforms are present, but implementation is not yet present as I do not have an environment to test these in.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Thanks for the patch. As was mentioned in #823, we can probably just use `SDL_ShowSimpleMessageBox` to handle these. That way, it's immediately implemented for all platforms.

We prefer this kind of platform-specific function to be part of our Platform namespace. However, in this case, I think we can just go with the SDL function directly.

**Comment by rdrdrdrd95** [comment]
I added that call as the platform default, so other platform specific calls are added it can be overridden. This way if you move away from SDL for a platform the place to implement this is there. I also moved everything to the OpenLoco::platform namesapce

**Comment by AaronVanGeffen** [comment]
You have moved it to the namespace, but not to the relevant files (`src/OpenLoco/Platform`).

Please also have a look at our [code style guidelines](https://github.com/OpenLoco/OpenLoco/wiki/Coding-Style).

**Review by AaronVanGeffen — CHANGES_REQUESTED** [review]
@rdrdrdrd95 Do you still intend to work on this? This would be a useful to have for user feedback.

As mentioned before, the PR does not currently follow our code style. I also do think the `SystemPopups` folder introduced is not necessary, especially if it is only calling into a function in the Ui namespace. The PR as-is refers to a missing function there, `Ui::showMessageBox`.

**Comment by rdrdrdrd95** [comment]
I will be attempting to do this this week. I have been fairly swamped with job and travel so my bandwidth for development has been reduced.

**Comment by AaronVanGeffen** [comment]
Replaced by #1104

**Pull request closed without merging**
