### PR TITLE
Fix #2162: Unlink Build Vehicle window when linked vehicle window is closed

### LINKED ISSUE #2162: Bug when creating more than one train at once.
**Version information:**
 - Platform: Windows 10
 - Version: 23.10
 - Build/commit: d980351f

**Describe the bug**
I create a new train, place it on the track, assign it destinations, start it and then close the new train's window. I click to create another new train, and I get an error message 'Can't add xxxx to Train yy... Must be stopped first'.

If the first train is stopped, creating a new loco adds this to the end of the first train even though it's window is closed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Build Trains.
2. Click on a new loco.
3. Add some rolling stock.
4. Drop train on the track.
5. Start the train.
6. Close the train window.
7. In the Build Trains window, click on another loco.
8. Error displayed.

**Expected behaviour**
It should start creating a new train after the first train's window has been closed.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by AaronVanGeffen**

### CODE REVIEW

**Comment by LeftofZen** [comment]
Doesn't seem to work?

https://www.youtube.com/watch?v=9S0L4DO-NnA

**Comment by AaronVanGeffen** [comment]
Ah, that's a bit surprising, given https://github.com/OpenLoco/OpenLoco/issues/2162#issuecomment-1875888722. I'll look at it in the morning.

**Comment by AaronVanGeffen** [comment]
@LeftofZen I've pushed a more comprehensive check. Could you re-test?

**Comment by FenderBender2** [comment]
If it helps I re-tested and got the following results. After creating the first train, the second train will be added to the first but the third creates a new train.

https://github.com/OpenLoco/OpenLoco/assets/121941598/0cbd37f8-47bb-406e-bdf8-43cc782b5ca3

**Comment by AaronVanGeffen** [comment]
> If it helps I re-tested and got the following results. After creating the first train, the second train will be added to the first but the third creates a new train.

What build number and hash did you use to test? (Lower-left of the title screen)

**Comment by FenderBender2** [comment]
My apologies. That behaviour in my video is from the v23.12 (dcd393ac on master) version. I have run a test using v23.12-8 (0d9f97ad on HEAD) and its working perfectly for me using the same test as @LeftofZen.

**Comment by LeftofZen** [comment]
@AaronVanGeffen Yep everything seems to work now.

**Comment by AaronVanGeffen** [comment]
Great! Could you approve the PR, then? :)

**Comment by LeftofZen** [comment]
Oh yeah haha, sorry been a long day

**Review by LeftofZen — APPROVED** [review]
Playtested, works as expected

**Pull request merged**
