### PR TITLE
Implement Create Airport

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Not tested much.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
There is a divergence in this.

**Comment by duncanspumpkin** [comment]
I think thats the last issue with this but as there are issues in common functions that are from before this MR i'm going to have to probably do new replays.

**Comment by duncanspumpkin** [comment]
This finally has no desync issues

**Comment by AaronVanGeffen** [comment]
Screenshot 2024-08-25 at 22 03 58

I think it shouldn't be possible to build airports this close to one another.

**Review by AaronVanGeffen — APPROVED** [review]

**Pull request merged**
