### PR TITLE
Fix crash in build menu

### PR DESCRIPTION
**Pull request by duncanspumpkin**

### CODE REVIEW

**Review by LeftofZen — APPROVED** [review]
I personally didn't test these as I don't get the crash/couldn't repro it, but they seem sensible

**Comment by duncanspumpkin** [comment]
@janisozaur any reason the warnings aren't displaying on this pr?

**Comment by janisozaur** [comment]
But they are:
Screenshot_2022-04-16-19-37-51-14_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by duncanspumpkin** [comment]
Well that is weird its not showing for me.

**Comment by janisozaur** [comment]
I think they don't show immediately, only a moment after all builds are done. Perhaps you checked too soon?

**Pull request merged**
