### PR TITLE
translation: simplified chinese

### PR DESCRIPTION
**Pull request by TransshipmentEnvoy**
Some items are not translated yet.

According to issue #304 and #580, all characters will be displayed as question marks, which means I can't check whether all translated items are correct.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Thank you for your contribution! I really hope we can get support for CJK languages into the game. It's high on my wish list, anyway. Unfortunately, we're a little short on devs and time…

Could you an entry for 'Chinese (Simplified)' along with your name to the contributors file as well?

**Comment by TransshipmentEnvoy** [comment]
I have appended an entry for 'Chinese (Simplified)' in CONTRIBUTORS.MD, section Translations.

I also update a few translation items

**Comment by TransshipmentEnvoy** [comment]
Should I use `git rebase` to merge these 3 commits into one commit and force push?

**Comment by AaronVanGeffen** [comment]
Thanks! No need to rebase, we can squash them into one through the GitHub interface.

**Review by AaronVanGeffen — APPROVED** [review]

**Comment by ychunlai** [comment]
各位老师好，请问设置成中文后显示为问号应该怎么办？我能为此做什么贡献吗？但是我不会骗程。

**Comment by telk5093** [comment]
> 各位老师好，请问设置成中文后显示为问号应该怎么办？我能为此做什么贡献吗？但是我不会编程。

See #304. Unfortunately it is not supported CJK languages yet. (And please, we can't read chinese without translator)

**Pull request merged**
