### PR TITLE
Ignore music playing state when game is paused

### PR DESCRIPTION
**Pull request by ilmoro93**
As reported in https://github.com/OpenLoco/OpenLoco/issues/2180, the music doesn't restart when the game is resumed from pause.

This PR fixes it by preventing _Play music_ option to be unselected by `cfg.musicPlaying = playMusic(mi.pathId, cfg.volume, false);` in `playBackgroundMusic()` when game `isPaused()`.

But there is still a problem: when resuming in Locomotion the music is actually resumed, while in OpenLoco it restarts from the beginning.

Moreover I have noticed that clicking _Load Saved Game_ in main menu also stops the music.

I don't know if we should solve everything in one PR or you can review and merge this little fix only.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
> But there is still a problem: when resuming in Locomotion the music is actually resumed, while in OpenLoco it restarts from the beginning.

Unlike vanilla, OpenLoco does not keep track of music progression. That much is currently delegated to the stream library (OpenAL). We could potentially reintroduce this, though, by querying track progression before the stream is cut.

**Comment by ZehMatt** [comment]
> > But there is still a problem: when resuming in Locomotion the music is actually resumed, while in OpenLoco it restarts from the beginning.
> 
> Unlike vanilla, OpenLoco does not keep track of music progression. That much is currently delegated to the stream library (OpenAL). We could potentially reintroduce this, though, by querying track progression before the stream is cut.

Do we need to track the progress? I think pause/resume functionality exists in OpenAL so we don't have to do that ourselves.

**Comment by ilmoro93** [comment]
> > > But there is still a problem: when resuming in Locomotion the music is actually resumed, while in OpenLoco it restarts from the beginning.
> > 
> > 
> > Unlike vanilla, OpenLoco does not keep track of music progression. That much is currently delegated to the stream library (OpenAL). We could potentially reintroduce this, though, by querying track progression before the stream is cut.
> 
> Do we need to track the progress? I think pause/resume functionality exists in OpenAL so we don't have to do that ourselves.

I have tried the `alSourcePause()` function of OpenAL. If I get a working solution I will make a PR in the next days to fix #2180 and to enable music resume after pause.

**Comment by ilmoro93** [comment]
I think `Audio::playMusic()` should not return bool. The return value is only used in `playBackgroundMusic()` and assigned to `cfg.musicPlaying`, which unselects the _Play music_ option, and I think this is wrong (see https://github.com/OpenLoco/OpenLoco/issues/2180#issuecomment-1989046050).
What do you think?

**Comment by LeftofZen** [comment]
perhaps a broader discussion; should the music pause at all when the user pauses the game? the ambient track does not pause, so perhaps either it should, or the music shouldn't

**Review by LeftofZen — DISMISSED** [review]
* functionality works but also introduces a bug - if you mute the audio with 
image
then the playlist cycles through tracks infinitely. this does not happen in 24.04
* needs changelog

**Comment by ilmoro93** [comment]
> perhaps a broader discussion; should the music pause at all when the user pauses the game? the ambient track does not pause, so perhaps either it should, or the music shouldn't

I think every sound should pause when the game is paused, like vanilla. I find it more intuitive, it makes it clear that game is playing when music resumes.

**Review by AaronVanGeffen — APPROVED** [review]

**Pull request merged**
