### PR TITLE
Refactor the passing of drawing context

### PR DESCRIPTION
**Pull request by ZehMatt**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Observing minor glitching in the frame counter:

Screenshot 2024-06-26 at 07 05 44

Also, I have unchecked the 'uncap frame limiter' option, but this indicator suggests the fps are in the hundreds??

**Comment by AaronVanGeffen** [comment]
Have not observed any weird glitches in the rendering, other than the uncap fps option potentially no longer working.

**Comment by ZehMatt** [comment]
> Have not observed any weird glitches in the rendering, other than the uncap fps option potentially no longer working.

I think its the FPS counter, I had to move that code so that probably broke it.

**Review by AaronVanGeffen — APPROVED** [review]
The issue with rendering the FPS counter has been resolved. Looks good to me :)

**Review by duncanspumpkin — APPROVED** [review]

**Pull request merged**
