### PR TITLE
Fix #1711. Create an initial user folder if it does not exist

### LINKED ISSUE #1711: Issue getting compiled Linux binary to start on Manjaro
Hi all,

I'm running Manjaro and I am trying to get the code running with the Locomotion files that I have.

I compiled the code in an Ubuntu docker container and the executable seems to be able to start.
image

I provide the folder to the Locomotion installation directory. I installed it from the CD via Steam and Proton.
**/home/tv/.steam/steam/steamapps/compatdata/3018806553/pfx/drive_c/Program Files (x86)/Atari/Locomotion**

It then returns that it cannot find g1.dat

I thought maybe the issue was with Program Files having a space in it, so I copied the folder to my home folder.

image

It complains about g1.dat again. I notice the extension originally has capital .DAT
I rename it and try again.
Same error.

Any ideas as to where to go from here?

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Added intellisense hint for WSL2

### CODE REVIEW

**Review by AaronVanGeffen — COMMENTED** [review]
LGTM, but does it fully solve the issue reported?

Should probably be added to the changelog, too

**Review by janisozaur — APPROVED** [review]
Not truly a fan of having both items in single commit, but still ok

**Comment by duncanspumpkin** [comment]
> LGTM, but does it fully solve the issue reported?
> 
> Should probably be added to the changelog, too

Well it fixes one of the issues found

**Review by AaronVanGeffen — APPROVED** [review]
Could you add a changelog entry, then?

**Review by AaronVanGeffen — APPROVED** [review]

**Pull request merged**
