### PR TITLE
RemoveIndustry Game Command

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Complete

### CODE REVIEW

**Comment by LeftofZen** [comment]
Removing an industry *costs* money. Is it supposed to be that way? Normally selling things will give you money.

**Comment by shusaura85** [comment]
Isn't it because the player doesn't own the industries? You get money when you sell infrastructure and vehicles you own. It's the same when you remove buildings from towns. It costs money to clear something that the player doesn't own.

**Comment by LeftofZen** [comment]
Good point, that makes sense and I'm fine with that behaviour, just wanted to check with duncan that's the intended behaviour

**Comment by AaronVanGeffen** [comment]
> Isn't it because the player doesn't own the industries? You get money when you sell infrastructure and vehicles you own. It's the same when you remove buildings from towns. It costs money to clear something that the player doesn't own.

Yes. This is true even for industries that the player has invested in (i.e. built during normal gameplay, rather than in sandbox mode or the scenario editor).

**Comment by LeftofZen** [comment]
Cool, well then I have no problems with this pr, I tested it and it seems to work perfectly for me. Another person testing would be good too

**Review by LeftofZen — APPROVED** [review]
I had no issues with this when I reviewed a few days ago, it worked as described

**Comment by gdiniz95** [comment]
Where can I find this command?

**Comment by AaronVanGeffen** [comment]
> Where can I find this command?

In the scenario editor, you can remove any industry that exists on the world map. These features can also enabled in-game by enabling the 'sandbox mode' cheat.

**Comment by gdiniz95** [comment]
Thanks!

**Pull request merged**
