### PR TITLE
Update CI images, add new distros

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Review by IntelOrca — APPROVED** [review]

**Review by AaronVanGeffen — CHANGES_REQUESTED** [review]
Let's hold off on merging this before the new CI jobs actually pass. Could you indicate what's needed to get them passing? (e.g. rapidyaml switchover?)

**Comment by janisozaur** [comment]
There are currently (at least) 2 issues:
1. yaml-cpp package not available in focal+ (see #1007)
2. jammy not cloning the project properly

**Comment by AaronVanGeffen** [comment]
This has been included into #1576, correct?

**Comment by janisozaur** [comment]
Implemented in #1576

**Pull request closed without merging**
