### PR TITLE
Replaced instances of Audio::playSound(soundId, pan) per issue #1407

### PR DESCRIPTION
**Pull request by memellis**
Did some manual testing to verify changes worked.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
There is also the users in the Vehicle window.`Audio::playSound(Audio::SoundId::waypoint, { x, y, Input::getDragLastLocation().x }, Input::getDragLastLocation().x);` should be `Audio::playSound(Audio::SoundId::waypoint, Input::getDragLastLocation().x);`

**Comment by memellis** [comment]
After a bit of branch commit confusion I've addressed the uses in Vehicle window.

**Comment by duncanspumpkin** [comment]
There looks to be a little code formatting issue. Could you address it.

**Comment by memellis** [comment]
Code formatter issued now addressed.

**Pull request merged**
