### PR TITLE
Fix #945: Station construction preview image is using wrong colours

### LINKED ISSUE #945: Station construction preview image wrong
**Version information:**
 - Platform: Linux
 - Version: 21.04.1+
 - Build/commit: 74b0669d2ec8e39c04d510920f23200a144cab1b

In the construction window, station pieces are not rendered in the right colours.

Screenshot_20210423_191050

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
| Before | After |
| - | - |
| Screenshot_20210423_191050 | Screenshot_20210423_191757 |

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]
You should move the +1 to be inside the function. The +1 is on the image id base not the image id encoded with colour.

**Comment by duncanspumpkin** [comment]
I don't know enough about the colour changes to know if they are correct. Does it make sense the outline calls are they not palette indexs.

**Comment by AaronVanGeffen** [comment]
> I don't know enough about the colour changes to know if they are correct. Does it make sense the outline calls are they not palette indexs.

Hmm, I think you may be right. I've pushed a change to use palette indexes instead.

@marijnvdwerf, any thoughts on this?

**Comment by AaronVanGeffen** [comment]
I've dropped the refactor commits from this PR. Let's merge this PR with just the fix. I'll then open another PR to do more refactoring on the construction window.

**Pull request merged**
