### PR TITLE
Implement the two industry animation functions

### PR DESCRIPTION
**Pull request by duncanspumpkin**

### CODE REVIEW

**Review by AaronVanGeffen — CHANGES_REQUESTED** [review]
The animation for Oil Wells no longer works correctly on this PR. Should be clear in the 'Oil Oasis' scenario for example.

**Comment by duncanspumpkin** [comment]
That should be all the bugs ironed out.

**Comment by duncanspumpkin** [comment]
Passes a 1000000 tick lets play save.

**Comment by AaronVanGeffen** [comment]
The oil well animations are looking fine now, but the oil refinery is still having problems. The flames seem to be having similar speed issues to what the oil wells were having.

**Review by AaronVanGeffen — APPROVED** [review]
All good now, as far as I can tell :+1:

**Pull request merged**
