### PR TITLE
Vehicle list window

### PR DESCRIPTION
**Pull request by reinaldorauch**
Implements the Vehicle List window

Not finished of course, will try to work on this in my (sparse) free time

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
As discussed on Discord, thanks for your interest in working on this! You've chosen a relatively complicated window to implement. Let us know if you need any help.

**Comment by reinaldorauch** [comment]
> As discussed on Discord, thanks for your interest in working on this! You've chosen a relatively complicated window to implement. Let us know if you need any help.

Sure, i'll let you know. I didn't had time to work in this last week. If you feel that i'm taking too long to implement, anyone be free to take this over, no hard feelings :P

**Comment by AaronVanGeffen** [comment]
I've pitched in to further the window implementation. My current implementation looks like this:
Screenshot (6)

Compare this to master:
Screenshot (4)

The window frame does not render correctly (not highlighted), and there's a glitch in the top left corner. Also problematic is the window resizing not working: a mousedown on the resize handle is treated as a mousedown on the reliability header.

I've not yet figured out what's causing these issues; they might go away with more implementation. I expect I'll be a bit busier next week, so help is welcome.

**Comment by AaronVanGeffen** [comment]
In the process of rebasing this PR, I accidentally pushed master instead of the rebased branch, deleting the branch. Since I can't reopen the PR, I'm continuing in #878.

**Pull request closed without merging**
