### PR TITLE
Remove unnecessary clang-format toggles

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
@janisozaur Could you help getting a new version of clang-format deployed to Travis?

**Comment by janisozaur** [comment]
https://github.com/angular/clang-format/blob/master/bin/linux_x64/clang-format has a static build of clang-format that I think is best approach. They occasionally update the binary, though I don't know the process or frequency. I suggest we use that, take directly from master and have the build identify itself before applying the formatting.

Do you want me to implement that?

**Comment by AaronVanGeffen** [comment]
For OpenRCT2, I notice you'd set up a Docker image for clang-format purposes. I somewhat prefer that approach, as we'd have more control over the binary we'd end up running.

However, if you feel the source above is trustworthy enough, I trust your judgement.

**Comment by janisozaur** [comment]
If you needed an older version, the docker approach is less flexible. If you need newer version, you still need to update your container, possibly switch to another one. The angular repo seems to be updated frequently enough for our needs and if you need older version for whatever reason, they are all available from history. I prefer this approach over the docker that's used in OpenRCT2 and which I have not set up.

**Comment by marijnvdwerf** [comment]
I don't care either way. Just downloading the angular executable seems to be a lot easier though

**Comment by AaronVanGeffen** [comment]
@janisozaur If you have time, could you pick this up?

**Pull request merged**
