### PR TITLE
Use the logging library more

### PR DESCRIPTION
**Pull request by duncanspumpkin**
A tiny bit of the c++20 changes and general improvement. @ZehMatt there is still a lot of cout/printf in the command line stuff were you thinking that would call libfmt directly?

### CODE REVIEW

**Comment by IntelOrca** [comment]
Can we maybe alias `Diagnostics::Logging` in some way? It is currently a bit of a mouthful, maybe just `Log::info`?

`using Log = Diagnostics::Logging;`?

**Comment by ZehMatt** [comment]
> Can we maybe alias `Diagnostics::Logging` in some way? It is currently a bit of a mouthful, maybe just `Log::info`?
> 
> `using Log = Diagnostics::Logging;`?
> 
> Also I am a bit surprised we need `\n` in each log call.

We can definitely have `namespace Log = Diagnostics::Logging` at the top of the file, I also do agree on the newline being a bit a silly, thats however more of a legacy/refactoring reason to why its still this way, its worth changing for when I phase out the rest however.

I think if there are any other concerns regarding the logging code now would be the time to say so, I'm surprised you said nothing when I made the first PR.

**Comment by AaronVanGeffen** [comment]
> Can we maybe alias `Diagnostics::Logging` in some way? It is currently a bit of a mouthful, maybe just `Log::info`?

I propose we just use `using namespace OpenLoco::Diagnostics;` to get `Logging` in.

> Also I am a bit surprised we need `\n` in each log call.

We don't need to. I think that's just a leftover from the old `printf` statements these calls replace.

**Comment by ZehMatt** [comment]
Actually I just checked we don't have to provide a new line, the callers should remove it.

**Comment by IntelOrca** [comment]
> I think if there are any other concerns regarding the logging code now would be the time to say so, I'm surprised you said nothing when I made the first PR.

Because it was better than no logging, or what we were doing previously. Things like this can be done as follow ups.

**Comment by ZehMatt** [comment]
> > I think if there are any other concerns regarding the logging code now would be the time to say so, I'm surprised you said nothing when I made the first PR.
> 
> Because it was better than no logging, or what we were doing previously. Things like this can be done as follow ups. If the new line isn't required, maybe that is why I didn't say anything about it in the original PR 😅

I definitely outplayed myself on this one, I was under the impression somehow that this is an issue as I've only looked at the comment since I got tagged, so my bad. But yeah one of the design goals was that sinks are ultimately responsible for how it ends up in the output.

**Pull request merged**
