### PR TITLE
Implement EntityManager::updateMonthly

### PR DESCRIPTION
**Pull request by duncanspumpkin**

### CODE REVIEW

**Review by LeftofZen — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
Diverging on 1000 tick and 10000 tick.

**Comment by duncanspumpkin** [comment]
totalRefundCost is calculated wrong.

**Comment by duncanspumpkin** [comment]
well that was obvious. I wasn't actually calling the function.

**Comment by duncanspumpkin** [comment]
No longer diverges on the 1000 tick. I haven't run the 10000tick in a while but im seeing a divergence but in the tile elements part of the file and since that is subject to reordering I'm not sure I can say much about it.

**Pull request merged**
