### PR TITLE
Paint surface

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Complete!

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
To check the results from this PR, I've created two sets of giant screenshots of the usual Matsku Playthrough save. Both sets contain screenshots of the four rotations. To make these screenshots, I hacked the game loop to not progress at all, effectively pausing the game.

Observations:
* Areas under bridges are no longer shaded.
* Water seems to be painted slightly differently. The tone is notably darker. Could it be off by one in an animation, somehow?
*

**Comment by duncanspumpkin** [comment]
Fixed those two issues.

**Comment by AaronVanGeffen** [comment]
Can confirm water and shadows now appear properly.

Found one more issue with the Matsku map, but only on one rotation. Consider the edges around this city:

On master:
Screenshot 2024-05-15 at 14 20 23

On this PR:
Screenshot 2024-05-15 at 14 20 38

Diff:
Screenshot 2024-05-15 at 14 19 00

**Review by AaronVanGeffen — APPROVED** [review]
Everything looks to be in order. Impressive work!

**Pull request merged**
